site_name: NCBS Hippo
site_url: https://ncbs.res.in/hippo
site_author: Dilawar Singh <dilawars@ncbs.res.in>
copyright: 'Copyright &copy; 2016-2020 Dilawar Singh'
repo_url: https://github.com/dilawar/HippoApp
theme:
    name: material

nav:
    - Home: index.md
    - User Manual: user_manual.md
    - Admin Manual:
        - BookMyVenue Admin manual: bmv_admin_manual.md
        - Acadmic Admin Manual: acadic_admin_manual.md
        - Admin Manual: admin_manual.md
    - Developer Documents: developer.md
    - Bug tracker: https://github.com/dilawar/hippo/issues

markdown_extensions:
    - admonition
    - toc
    - attr_list
    - fontawesome_markdown
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
    - js/fa.js
