version: '3'
services:
    hippo:
        image: dilawars/hippo:${VERSION:-latest}
        build:
            context: suse
        environment:
            - DEBUG="1"
        volumes:
            - ./..:/srv/www/htdocs/hippo:rw
            - /tmp:/tmp
            - /var/log:/var/log:rw 
            - /etc/hipporc:/etc/hipporc
        network_mode: host
